repositories:
- namespace: splitgraph
  repository: socrata
  # Catalog-specific metadata for the repository. Optional.
  metadata:
    readme:
      text: Readme
    description: Description of the repository
    topics:
    - sample_topic
  # Data source settings for the repository. Optional.
  external:
    # Name of the credential that the plugin uses. This can also be a credential_id if the
    # credential is already registered on Splitgraph.
    credential: socrata
    plugin: socrata
    # Plugin-specific parameters matching the plugin's parameters schema
    params:
      domain: ''  # REQUIRED. Socrata domain, for example, data.albanyny.gov
      batch_size: 1000 # Amount of rows to fetch from Socrata per request (limit parameter)
    tables:
      sample_table:
        # Plugin-specific table parameters matching the plugin's schema
        options:
          socrata_id: ''  # REQUIRED. Socrata dataset ID, e.g. xzkq-xp2w
          cursor_fields: [] # Replication cursor. Column(s) to use as a replication cursor. This must be always increasing in the source table and is used to track which rows should be replicated.
        # Schema of the table, a list of objects with `name` and `type`. If set to `[]`, will infer. 
        schema: []
    # Whether live querying is enabled for the plugin (creates a "live" tag in the
    # repository proxying to the data source). The plugin must support live querying.
    is_live: true
    # Ingestion schedule settings. Disable this if you're using GitHub Actions or other methods
    # to trigger ingestion.
    schedule:
- namespace: splitgraph
  repository: dbt-sample
  external:
    plugin: dbt
    credential: dbt-sample
    params:
      sources:
      - dbt_source_name: splitgraph_socrata
        namespace: splitgraph
        repository: socrata
        hash_or_tag: latest
      git_branch: $THIS_SHA
    is_live: false
    tables: {}
  metadata:
    description: Sample dbt model
    readme:
      text: "## Sample dbt model\n\nThis is an autogenerated model referencing data\
        \ from:\n\n  * [/splitgraph/socrata](/splitgraph/socrata)"
