name: Build datasets on Splitgraph
on: workflow_dispatch
jobs:
  for_hire_vehicles:
    name: Build splitgraph-demo/for-hire-vehicles
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Splitgraph
      uses: splitgraph/setup-splitgraph@master
      with:
        splitgraph_deployment_url: splitgraph.com
        splitgraph_api_key: ${{ secrets.SPLITGRAPH_API_KEY }}
        splitgraph_api_secret: ${{ secrets.SPLITGRAPH_API_SECRET }}
    - name: Run sgr cloud load to set up metadata and data source settings
      # Add --initial-private to load the data into a private repository (we'll
      # make this repository public for demo purposes)
      run: sgr cloud load --remote splitgraph -f splitgraph.yml
        -f splitgraph.credentials.yml splitgraph-demo/for-hire-vehicles
      shell: bash
    # Run sgr cloud sync without using splitgraph.yml, which will reuse the existing
    # data source settings from splitgraph-demo/for-hire-vehicles
    - name: Run sgr cloud sync to perform the data load
      run: sgr cloud sync --remote splitgraph --wait splitgraph-demo/for-hire-vehicles
      shell: bash
  for_hire_vehicles_summary:
    name: Build splitgraph-demo/for-hire-vehicles-summary
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Splitgraph
      uses: splitgraph/setup-splitgraph@master
      with:
        splitgraph_deployment_url: splitgraph.com
        splitgraph_api_key: ${{ secrets.SPLITGRAPH_API_KEY }}
        splitgraph_api_secret: ${{ secrets.SPLITGRAPH_API_SECRET }}
    - name: Set up dbt Git URL
      run: sed -i "s|\$THIS_REPO_URL|https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY|g"
        splitgraph.credentials.yml && sed -i "s|\$THIS_SHA|$GITHUB_SHA|g" splitgraph.yml
      shell: bash
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Run sgr cloud sync to perform the data load
      # Add --initial-private to load the data into a private repository.
      run: sgr cloud sync --remote splitgraph --use-file -f splitgraph.yml
        -f splitgraph.credentials.yml --wait  splitgraph-demo/for-hire-vehicles-summary
      shell: bash
      # Set up the metadata too (data source etc). Note that we won't be able to trigger dbt
      # model runs from Splitgraph in this case, as this will use a temporary GitHub URL to
      # this project -- this is just to get the dbt icon to show up.
    - name: Run sgr cloud load to set up metadata
      run: sgr cloud load --remote splitgraph -f splitgraph.yml -f
        splitgraph.credentials.yml splitgraph-demo/for-hire-vehicles-summary
      shell: bash
    needs:
    - for_hire_vehicles
